eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8686/eureka/
server:
    port: 8787
spring:
    application:
        name: ship-service